<script>
	import * as Icon from '$lib';
</script>

<Icon.Cil3d />
<Icon.Cil4k />
<Icon.CilAccountLogout />
<Icon.CilActionRedo />
<Icon.CilActionUndo />
<Icon.CilAddressBook />
<Icon.CilAirplaneMode />
<Icon.CilAirplaneModeOff />
<Icon.CilAirplay />
<Icon.CilAlarm />
<Icon.CilAlbum />
<Icon.CilAlignCenter />
<Icon.CilAlignLeft />
<Icon.CilAlignRight />
<Icon.CilAmericanFootball />
<Icon.CilAnimal />
<Icon.CilAperture />
<Icon.CilApple />
<Icon.CilApplications />
<Icon.CilApplicationsSettings />
<Icon.CilApps />
<Icon.CilAppsSettings />
<Icon.CilArrowBottom />
<Icon.CilArrowCircleBottom />
<Icon.CilArrowCircleLeft />
<Icon.CilArrowCircleRight />
<Icon.CilArrowCircleTop />
<Icon.CilArrowLeft />
<Icon.CilArrowRight />
<Icon.CilArrowThickBottom />
<Icon.CilArrowThickFromBottom />
<Icon.CilArrowThickFromLeft />
<Icon.CilArrowThickFromRight />
<Icon.CilArrowThickFromTop />
<Icon.CilArrowThickLeft />
<Icon.CilArrowThickRight />
<Icon.CilArrowThickToBottom />
<Icon.CilArrowThickToLeft />
<Icon.CilArrowThickToRight />
<Icon.CilArrowThickToTop />
<Icon.CilArrowThickTop />
<Icon.CilArrowTop />
<Icon.CilAssistiveListeningSystem />
<Icon.CilAsterisk />
<Icon.CilAsteriskCircle />
<Icon.CilAt />
<Icon.CilAudio />
<Icon.CilAudioDescription />
<Icon.CilAudioSpectrum />
<Icon.CilAvTimer />
<Icon.CilBaby />
<Icon.CilBabyCarriage />
<Icon.CilBackspace />
<Icon.CilBadge />
<Icon.CilBalanceScale />
<Icon.CilBan />
<Icon.CilBank />
<Icon.CilBarChart />
<Icon.CilBarcode />
<Icon.CilBaseball />
<Icon.CilBasket />
<Icon.CilBasketball />
<Icon.CilBath />
<Icon.CilBathroom />
<Icon.CilBattery0 />
<Icon.CilBattery3 />
<Icon.CilBattery5 />
<Icon.CilBatteryAlert />
<Icon.CilBatteryEmpty />
<Icon.CilBatteryFull />
<Icon.CilBatterySlash />
<Icon.CilBeachAccess />
<Icon.CilBeaker />
<Icon.CilBed />
<Icon.CilBell />
<Icon.CilBellExclamation />
<Icon.CilBike />
<Icon.CilBirthdayCake />
<Icon.CilBlind />
<Icon.CilBluetooth />
<Icon.CilBlur />
<Icon.CilBlurCircular />
<Icon.CilBlurLinear />
<Icon.CilBoatAlt />
<Icon.CilBold />
<Icon.CilBolt />
<Icon.CilBoltCircle />
<Icon.CilBook />
<Icon.CilBookmark />
<Icon.CilBorderAll />
<Icon.CilBorderBottom />
<Icon.CilBorderClear />
<Icon.CilBorderHorizontal />
<Icon.CilBorderInner />
<Icon.CilBorderLeft />
<Icon.CilBorderOuter />
<Icon.CilBorderRight />
<Icon.CilBorderStyle />
<Icon.CilBorderTop />
<Icon.CilBorderVertical />
<Icon.CilBowling />
<Icon.CilBraille />
<Icon.CilBriefcase />
<Icon.CilBrightness />
<Icon.CilBritishPound />
<Icon.CilBrowser />
<Icon.CilBrush />
<Icon.CilBrushAlt />
<Icon.CilBug />
<Icon.CilBuilding />
<Icon.CilBullhorn />
<Icon.CilBurger />
<Icon.CilBurn />
<Icon.CilBusAlt />
<Icon.CilCalculator />
<Icon.CilCalendar />
<Icon.CilCalendarCheck />
<Icon.CilCamera />
<Icon.CilCameraControl />
<Icon.CilCameraRoll />
<Icon.CilCarAlt />
<Icon.CilCaretBottom />
<Icon.CilCaretLeft />
<Icon.CilCaretRight />
<Icon.CilCaretTop />
<Icon.CilCart />
<Icon.CilCash />
<Icon.CilCasino />
<Icon.CilCast />
<Icon.CilCat />
<Icon.CilCc />
<Icon.CilCenterFocus />
<Icon.CilChart />
<Icon.CilChartLine />
<Icon.CilChartPie />
<Icon.CilChatBubble />
<Icon.CilCheck />
<Icon.CilCheckAlt />
<Icon.CilCheckCircle />
<Icon.CilChevronBottom />
<Icon.CilChevronCircleDownAlt />
<Icon.CilChevronCircleLeftAlt />
<Icon.CilChevronCircleRightAlt />
<Icon.CilChevronCircleUpAlt />
<Icon.CilChevronDoubleDown />
<Icon.CilChevronDoubleLeft />
<Icon.CilChevronDoubleRight />
<Icon.CilChevronDoubleUp />
<Icon.CilChevronLeft />
<Icon.CilChevronRight />
<Icon.CilChevronTop />
<Icon.CilChild />
<Icon.CilChildFriendly />
<Icon.CilCircle />
<Icon.CilClearAll />
<Icon.CilClipboard />
<Icon.CilClock />
<Icon.CilClone />
<Icon.CilClosedCaptioning />
<Icon.CilCloud />
<Icon.CilCloudDownload />
<Icon.CilCloudUpload />
<Icon.CilCloudy />
<Icon.CilCode />
<Icon.CilCoffee />
<Icon.CilCog />
<Icon.CilColorBorder />
<Icon.CilColorFill />
<Icon.CilColorPalette />
<Icon.CilColumns />
<Icon.CilCommand />
<Icon.CilCommentBubble />
<Icon.CilCommentSquare />
<Icon.CilCompass />
<Icon.CilCompress />
<Icon.CilContact />
<Icon.CilContrast />
<Icon.CilControl />
<Icon.CilCopy />
<Icon.CilCouch />
<Icon.CilCreditCard />
<Icon.CilCrop />
<Icon.CilCropRotate />
<Icon.CilCursor />
<Icon.CilCursorMove />
<Icon.CilCut />
<Icon.CilDataTransferDown />
<Icon.CilDataTransferUp />
<Icon.CilDeaf />
<Icon.CilDelete />
<Icon.CilDescription />
<Icon.CilDevices />
<Icon.CilDialpad />
<Icon.CilDiamond />
<Icon.CilDinner />
<Icon.CilDisabled />
<Icon.CilDog />
<Icon.CilDollar />
<Icon.CilDoor />
<Icon.CilDoubleQuoteSansLeft />
<Icon.CilDoubleQuoteSansRight />
<Icon.CilDrink />
<Icon.CilDrinkAlcohol />
<Icon.CilDrop />
<Icon.CilEco />
<Icon.CilEducation />
<Icon.CilElevator />
<Icon.CilEnvelopeClosed />
<Icon.CilEnvelopeLetter />
<Icon.CilEnvelopeOpen />
<Icon.CilEqualizer />
<Icon.CilEthernet />
<Icon.CilEuro />
<Icon.CilExcerpt />
<Icon.CilExitToApp />
<Icon.CilExpandDown />
<Icon.CilExpandLeft />
<Icon.CilExpandRight />
<Icon.CilExpandUp />
<Icon.CilExposure />
<Icon.CilExternalLink />
<Icon.CilEyedropper />
<Icon.CilFace />
<Icon.CilFaceDead />
<Icon.CilFactory />
<Icon.CilFactorySlash />
<Icon.CilFastfood />
<Icon.CilFax />
<Icon.CilFeaturedPlaylist />
<Icon.CilFile />
<Icon.CilFilter />
<Icon.CilFilterFrames />
<Icon.CilFilterPhoto />
<Icon.CilFilterSquare />
<Icon.CilFilterX />
<Icon.CilFindInPage />
<Icon.CilFingerprint />
<Icon.CilFire />
<Icon.CilFlagAlt />
<Icon.CilFlightTakeoff />
<Icon.CilFlip />
<Icon.CilFlipToBack />
<Icon.CilFlipToFront />
<Icon.CilFlower />
<Icon.CilFolder />
<Icon.CilFolderOpen />
<Icon.CilFont />
<Icon.CilFootball />
<Icon.CilFork />
<Icon.CilFridge />
<Icon.CilFrown />
<Icon.CilFullscreen />
<Icon.CilFullscreenExit />
<Icon.CilFunctions />
<Icon.CilFunctionsAlt />
<Icon.CilGamepad />
<Icon.CilGarage />
<Icon.CilGem />
<Icon.CilGif />
<Icon.CilGift />
<Icon.CilGlobeAlt />
<Icon.CilGolf />
<Icon.CilGolfAlt />
<Icon.CilGradient />
<Icon.CilGrain />
<Icon.CilGraph />
<Icon.CilGrid />
<Icon.CilGridSlash />
<Icon.CilGroup />
<Icon.CilHamburgerMenu />
<Icon.CilHandPointDown />
<Icon.CilHandPointLeft />
<Icon.CilHandPointRight />
<Icon.CilHandPointUp />
<Icon.CilHandshake />
<Icon.CilHappy />
<Icon.CilHd />
<Icon.CilHdr />
<Icon.CilHeader />
<Icon.CilHeadphones />
<Icon.CilHealing />
<Icon.CilHeart />
<Icon.CilHighlighter />
<Icon.CilHighligt />
<Icon.CilHistory />
<Icon.CilHome />
<Icon.CilHospital />
<Icon.CilHotTub />
<Icon.CilHouse />
<Icon.CilHttps />
<Icon.CilImage />
<Icon.CilImageBroken />
<Icon.CilImagePlus />
<Icon.CilInbox />
<Icon.CilIndentDecrease />
<Icon.CilIndentIncrease />
<Icon.CilIndustry />
<Icon.CilIndustrySlash />
<Icon.CilInfinity />
<Icon.CilInfo />
<Icon.CilInput />
<Icon.CilInputHdmi />
<Icon.CilInputPower />
<Icon.CilInstitution />
<Icon.CilItalic />
<Icon.CilJustifyCenter />
<Icon.CilJustifyLeft />
<Icon.CilJustifyRight />
<Icon.CilKeyboard />
<Icon.CilLan />
<Icon.CilLanguage />
<Icon.CilLaptop />
<Icon.CilLayers />
<Icon.CilLeaf />
<Icon.CilLemon />
<Icon.CilLevelDown />
<Icon.CilLevelUp />
<Icon.CilLibrary />
<Icon.CilLibraryAdd />
<Icon.CilLibraryBuilding />
<Icon.CilLifeRing />
<Icon.CilLightbulb />
<Icon.CilLineSpacing />
<Icon.CilLineStyle />
<Icon.CilLineWeight />
<Icon.CilLink />
<Icon.CilLinkAlt />
<Icon.CilLinkBroken />
<Icon.CilList />
<Icon.CilListFilter />
<Icon.CilListHighPriority />
<Icon.CilListLowPriority />
<Icon.CilListNumbered />
<Icon.CilListNumberedRtl />
<Icon.CilListRich />
<Icon.CilLocationPin />
<Icon.CilLockLocked />
<Icon.CilLockUnlocked />
<Icon.CilLocomotive />
<Icon.CilLoop />
<Icon.CilLoop1 />
<Icon.CilLoopCircular />
<Icon.CilLowVision />
<Icon.CilMagnifyingGlass />
<Icon.CilMap />
<Icon.CilMediaEject />
<Icon.CilMediaPause />
<Icon.CilMediaPlay />
<Icon.CilMediaRecord />
<Icon.CilMediaSkipBackward />
<Icon.CilMediaSkipForward />
<Icon.CilMediaStepBackward />
<Icon.CilMediaStepForward />
<Icon.CilMediaStop />
<Icon.CilMedicalCross />
<Icon.CilMeh />
<Icon.CilMemory />
<Icon.CilMenu />
<Icon.CilMic />
<Icon.CilMicrophone />
<Icon.CilMinus />
<Icon.CilMobile />
<Icon.CilMobileLandscape />
<Icon.CilMoney />
<Icon.CilMonitor />
<Icon.CilMoodBad />
<Icon.CilMoodGood />
<Icon.CilMoodVeryBad />
<Icon.CilMoodVeryGood />
<Icon.CilMoon />
<Icon.CilMouse />
<Icon.CilMouthSlash />
<Icon.CilMove />
<Icon.CilMovie />
<Icon.CilMug />
<Icon.CilMugTea />
<Icon.CilMusicNote />
<Icon.CilNewspaper />
<Icon.CilNoteAdd />
<Icon.CilNotes />
<Icon.CilObjectGroup />
<Icon.CilObjectUngroup />
<Icon.CilOpacity />
<Icon.CilOpentype />
<Icon.CilOptions />
<Icon.CilPaint />
<Icon.CilPaintBucket />
<Icon.CilPaperPlane />
<Icon.CilPaperclip />
<Icon.CilParagraph />
<Icon.CilPaw />
<Icon.CilPen />
<Icon.CilPenAlt />
<Icon.CilPenNib />
<Icon.CilPencil />
<Icon.CilPeople />
<Icon.CilPhone />
<Icon.CilPin />
<Icon.CilPizza />
<Icon.CilPlant />
<Icon.CilPlaylistAdd />
<Icon.CilPlus />
<Icon.CilPool />
<Icon.CilPowerStandby />
<Icon.CilPregnant />
<Icon.CilPrint />
<Icon.CilPushchair />
<Icon.CilPuzzle />
<Icon.CilQrCode />
<Icon.CilRain />
<Icon.CilRectangle />
<Icon.CilRecycle />
<Icon.CilReload />
<Icon.CilReportSlash />
<Icon.CilResizeBoth />
<Icon.CilResizeHeight />
<Icon.CilResizeWidth />
<Icon.CilRestaurant />
<Icon.CilRoom />
<Icon.CilRouter />
<Icon.CilRowing />
<Icon.CilRss />
<Icon.CilRuble />
<Icon.CilRunning />
<Icon.CilSad />
<Icon.CilSatelite />
<Icon.CilSave />
<Icon.CilSchool />
<Icon.CilScreenDesktop />
<Icon.CilScreenSmartphone />
<Icon.CilScrubber />
<Icon.CilSearch />
<Icon.CilSend />
<Icon.CilSettings />
<Icon.CilShare />
<Icon.CilShareAll />
<Icon.CilShareAlt />
<Icon.CilShareBoxed />
<Icon.CilShieldAlt />
<Icon.CilShortText />
<Icon.CilShower />
<Icon.CilSignLanguage />
<Icon.CilSignalCellular0 />
<Icon.CilSignalCellular3 />
<Icon.CilSignalCellular4 />
<Icon.CilSim />
<Icon.CilSitemap />
<Icon.CilSmile />
<Icon.CilSmilePlus />
<Icon.CilSmoke />
<Icon.CilSmokeFree />
<Icon.CilSmokeSlash />
<Icon.CilSmokingRoom />
<Icon.CilSnowflake />
<Icon.CilSoccer />
<Icon.CilSofa />
<Icon.CilSortAlphaDown />
<Icon.CilSortAlphaUp />
<Icon.CilSortAscending />
<Icon.CilSortDescending />
<Icon.CilSortNumericDown />
<Icon.CilSortNumericUp />
<Icon.CilSpa />
<Icon.CilSpaceBar />
<Icon.CilSpeak />
<Icon.CilSpeaker />
<Icon.CilSpeech />
<Icon.CilSpeedometer />
<Icon.CilSpreadsheet />
<Icon.CilSquare />
<Icon.CilStar />
<Icon.CilStarHalf />
<Icon.CilStorage />
<Icon.CilStream />
<Icon.CilStrikethrough />
<Icon.CilSun />
<Icon.CilSwapHorizontal />
<Icon.CilSwapVertical />
<Icon.CilSwimming />
<Icon.CilSync />
<Icon.CilTablet />
<Icon.CilTag />
<Icon.CilTags />
<Icon.CilTask />
<Icon.CilTaxi />
<Icon.CilTennis />
<Icon.CilTennisBall />
<Icon.CilTerminal />
<Icon.CilTerrain />
<Icon.CilText />
<Icon.CilTextDirectionLtr />
<Icon.CilTextDirectionRtl />
<Icon.CilTextShapes />
<Icon.CilTextSize />
<Icon.CilTextSquare />
<Icon.CilTextStrike />
<Icon.CilThumbDown />
<Icon.CilThumbUp />
<Icon.CilToggleOff />
<Icon.CilToggleOn />
<Icon.CilToilet />
<Icon.CilTouchApp />
<Icon.CilTransfer />
<Icon.CilTranslate />
<Icon.CilTrash />
<Icon.CilTriangle />
<Icon.CilTruck />
<Icon.CilTv />
<Icon.CilUnderline />
<Icon.CilUsb />
<Icon.CilUser />
<Icon.CilUserFemale />
<Icon.CilUserFollow />
<Icon.CilUserPlus />
<Icon.CilUserUnfollow />
<Icon.CilUserX />
<Icon.CilVector />
<Icon.CilVerticalAlignBottom />
<Icon.CilVerticalAlignCenter />
<Icon.CilVerticalAlignTop />
<Icon.CilVideo />
<Icon.CilVideogame />
<Icon.CilViewColumn />
<Icon.CilViewModule />
<Icon.CilViewQuilt />
<Icon.CilViewStream />
<Icon.CilVoice />
<Icon.CilVoiceOverRecord />
<Icon.CilVolumeHigh />
<Icon.CilVolumeLow />
<Icon.CilVolumeOff />
<Icon.CilWalk />
<Icon.CilWallet />
<Icon.CilWallpaper />
<Icon.CilWarning />
<Icon.CilWatch />
<Icon.CilWc />
<Icon.CilWeightlifitng />
<Icon.CilWheelchair />
<Icon.CilWifiSignal0 />
<Icon.CilWifiSignal1 />
<Icon.CilWifiSignal2 />
<Icon.CilWifiSignal3 />
<Icon.CilWifiSignal4 />
<Icon.CilWifiSignalOff />
<Icon.CilWindow />
<Icon.CilWindowMaximize />
<Icon.CilWindowMinimize />
<Icon.CilWindowRestore />
<Icon.CilWrapText />
<Icon.CilX />
<Icon.CilXCircle />
<Icon.CilYen />
<Icon.CilZoom />
<Icon.CilZoomIn />
<Icon.CilZoomOut />
